config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  resources :posts
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 30 }
  validates_uniqueness_of :name
  has_many :post_categories
  has_many :posts, through: :post_categories
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 10, maximum: 30 }
  validates :description, presence: true, length: { minimum: 20, maximum: 200 }
  validates :user_id, presence: true
  has_many :post_categories
  has_many :categories, through: :post_categories
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end 

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 5, maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "User must be logged in to perform this action"
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category successfully created"
      redirect_to categories_path
    else
      render "new"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def show
    @category = Category.find(params[:id])
    @category_posts = @category.posts.paginate(page: params[:page], per_page: 5)
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Name of category updated"
      redirect_to category_path(@category)
    else
      render "edit"
    end
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end

    def require_admin
      if !logged_in? || (logged_in? && !current_user.admin?)
        flash[:danger] = "Admins only, no touching!"
        redirect_to categories_path
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 5)
  end

  def new
    @post = Post.new
  end

  def edit

  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:success] = "Blog created successfully"
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Blog updated successfully"
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def show

  end

  def destroy
    @post.destroy
    flash[:danger] = "Blog successfully deleted"
    redirect_to posts_path
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      if current_user != @post.user && !current_user.admin?
        flash[:danger] = "Invalid, can only edit and delete user's own blogs"
        redirect_to root_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Successfully Logged In"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Invalid login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:sucess] = "Logged Out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to my blog #{@user.username}"
      redirect_to users_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Account updated successfully"
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def show
    @user_posts = @user.posts.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "All posts created by the user are deleted"
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:danger] = "User can only edit their account"
        redirect_to root_path
      end
    end

    def require_admin
      if logged_in? && !current_user.admin?
        flash[:danger] = "Only admin users can do this action"
        redirect_to root_path
      end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    redirect_to posts_path if logged_in?
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<span class="badge">
  <%= link_to category.name, category_path(category) %>
</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class="form-group">
  <div class="control-label col-sm-2">
      <%= f.label :name %>
  </div>
  <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control", placeholder: "Category", autofocus: true %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary btn-lg" %>
  </div>
</div>
<% end %>

<div class="col-xs-4 col-xs-offset-4">
    [ <%= link_to "Cancel and return to blog listing", posts_path %> ]
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit Name of Category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">All Categories</h1>
  <div align="center">
      <% @categories.each do |category| %>
        <ul class="listing">
          <div class="row">
            <div class="well col-md-4 col-md-offset-4">
              <li class="post-title">
                <%= link_to category.name, category_path(category) %>
              </li>
              <li><small><%= pluralize(category.posts.count, "post") %></small></li>
            </div>
          </div>
        </ul>
        <% end %>
  </div>

app/views/categories/new.html.erb
<h1 align="center">Create a New Category</h1>
  <%= render "form" %>

app/views/categories/show.html.erb
<h1 align="center">Category Name:
  <%= @category.name %>
</h1>

<div align="center">
  <% if logged_in? && current_user.admin? %>
  <div class="row">
    <span class="badge"><%= link_to "Edit Name of Category", edit_category_path(@category) %></span>
  </div>
  <% end %>
    <%= will_paginate @category_posts %>
</div>
<%= render 'posts/post', obj: @category_posts %>
  <div align="center">
      <%= will_paginate @category_posts %>
  </div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Created and Designed by Elizabeth Rock for Franklin University class WEBD435
    </small>
  </footer>
</div>

app/views/layouts/_message.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= msg %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
  <%= link_to "Elizabeth's Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Posts", posts_path %></li>
          <li><%= link_to "Users", users_path %></li>
              <% if logged_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Posts<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "New Blog", new_post_path %></li>
                  </ul>
              </li>
              <% end %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "All Categories", categories_path %></li>
                    <% Category.all.each do |category| %>
                    <li><%= link_to category.name, category_path(category) %></li>
                    <% end %>
                    <% if logged_in? && current_user.admin? %>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "Create New Category", new_category_path %></li>
                    <% end %>
                  </ul>
                </li>
        </ul>

        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>

        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
          <li><%= link_to "Log Out", logout_path, method: :delete %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
                  <li><%= link_to "View Profile", user_path(current_user) %><%= "Admin" if current_user.admin? %></li>
                </ul>
            </li>
              <% else %>
              <li><%= link_to "Log In", login_path %></li>
              <li><%= link_to "Sign Up Now", signup_path %></li>
              <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/message' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>
<% if @post.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(@post.errors.count, "error") %>
            post couldn't be saved:
          </h2>
          <div class="panel-body">
            <ul>
              <%= @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%= render "shared/errors", obj: @post %>
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@post, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :title %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :title, class: "form-control", placeholder: "Title of Blog", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :description %>
      </div>
      <div class="col-sm-8">
        <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of Blog" %>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-sm-offset-2 col-sm-8">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <% cb.label(class: "checkbok-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary btn-lg' %>
      </div>
  </div>
  <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel and return to blog list", posts_path %> ]
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<% obj.each do |post| %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      <div class="post-title">
        <%= link_to post.title, post_path(post) %>
      </div>
      <div class="post-body">
        <%= truncate(post.description, length: 200) %>
        <div class="post-meta-details">
          <small>Created by: <%= post.user.username if post.user %>, <%= time_ago_in_words(post.created_at) %> ago, last updated: <%= time_ago_in_words(post.updated_at) %> ago</small>
        </div>
      </div>
      <% if post.categories.any? %>
      <p>Category: <%= render post.categories %></p>
      <% end %>
      <% if logged_in? && (current_user == post.user || current_user.admin?) %>
      <div class="post-actions">
        <%= link_to "Edit blog", edit_post_path(post), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete blog", posts_path(post), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/posts/edit.html.erb
<h1 align="center">Edit Blog</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1 align="center">List of blogs</h1>
<div align="center">

</div>
<%= render 'post', obj: @posts %>
<div align="center">

</div>

app/views/posts/new.html.erb
<h1 align="center">Create a new blog post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h2 align="center">Title: <%= @post.title %></h2>
<div class="well col-xs-9 col-xs-offset-2">
  <% if @post.user %>
  <ul class="listing">
    <div class="row center">
      <div class="col-md-4 col-md-offset-4">
        <li>Blog Created by:</li>
        <li class="post-title">
          <%= link_to @post.user.username, user_path(@post.user) %>
        </li>
        <li><small><%= pluralize(@post.user.posts.count, "post") if @post.user.posts %></small></li>
      </div>
    </div>
  </ul>
  <% end %>
  <h3 class="center description"><strong>Description:</strong></h3>
  <hr><%= simple_format(@post.description) %>
  <% if @post.categories.any? %>
  <p>Category: <%= render @post.categories %></p>
  <% end %>
  <div class="post-actions">
    <% if logged_in? && (current_user == @post.user || current_user.admin?) %>
    <%= link_to "Edit blog", edit_post_path(@post), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete blog", posts_path(@post), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all blogs", posts_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            post couldn't be saved:
          </h2>
          <div class="panel-body">
            <ul>
              <%= obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
  <div class="row">
    <div class="cols-xs-12">
      <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :username %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :username, class: "form-control", placeholder: "Enter your username", autofocus: true %>
          </div>
        </div>

        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :email %>
          </div>
          <div class="col-sm-8">
            <%= f.email_field :email, class: "form-control", placeholder: "Enter your email" %>
          </div>
        </div>

        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :password %>
          </div>
          <div class="col-sm-8">
            <%= f.password_field :password, class: "form-control", placeholder: "Enter your password" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit "Sign Up Now", class: "btn btn-primary btn-lg" %>
          </div>
        </div>
        <% end %>

        <div class="col-xs-2 col-xs-offset-4">
          [<%= link_to "Cancel and return to blog list", posts_path %> ]
        </div>
      </div>
    </div>

app/views/users/edit.html.erb
<h1 align="center">Edit Account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Bloggers</h1>
  <div align="center">
    <% @users.each do |user| %>
      <ul class="listing">
        <div class="row">
          <div class="well col-md-4 col-md-offset-4">
            <li class="article-title">
              <%= link_to user.username, user_path(user) %>
            </li>
            <li><small><%= pluralize(user.posts.count, "post") if user.posts %></small></li>
            <% if logged_in? and current_user.admin? %>
            <li><%= link_to "Delete User", user_path(user), method: :delete, data: { confirm: "Are you sure?" } %></li>
            <% end %>
          </div>
        </div>
      </ul>
<% end %>
  </div>

app/views/users/new.html.erb
<h1 align="center">Sign Up for Elizabeth's Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to
  <%= @user.username %>'s blog</h1>

  <h3 align="center">
    <%= @user.username %>'s blogs</h3>
    <div class="center">
    </div>
    <%= render 'posts/post', obj: @user.posts %>
    <div class="center">
    </div>

app/views/welcome/home.html.erb
<div class="center jumbotron">
  <h1>ELIZABETH'S BLOG</h1>
  <%= link_to "Sign Up", signup_path, class: "btn btn-primary btn-lg btn-xlarge" %>
</div>